# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-05 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_bank_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100, verbose_name='银行')),
                ('bankimg', models.ImageField(default='logo.png', upload_to='banklist', verbose_name='logo')),
            ],
        ),
    ]
