# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-09 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='颜色', max_length=30, verbose_name='颜色')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsimg', models.ImageField(default='normal.png', upload_to='static/img/goods', verbose_name='产品图')),
                ('goodsimgbig', models.ImageField(default='normal.png', upload_to='static/img/goods', verbose_name='产品大图')),
            ],
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goodsimg',
        ),
        migrations.AddField(
            model_name='goodsimg',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberapp.Goods'),
        ),
        migrations.AddField(
            model_name='goodscolor',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberapp.Goods'),
        ),
    ]
