# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-12 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0002_auto_20181109_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='listimg',
            field=models.ImageField(default='normal.png', upload_to='list', verbose_name='列表页图'),
        ),
        migrations.AlterField(
            model_name='goodsimg',
            name='goodsimg',
            field=models.ImageField(default='normal.png', upload_to='goods', verbose_name='产品图'),
        ),
        migrations.AlterField(
            model_name='goodsimg',
            name='goodsimgbig',
            field=models.ImageField(default='normal.png', upload_to='goods', verbose_name='产品大图'),
        ),
    ]
