# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-27 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0003_auto_20181112_1646'),
        ('cart', '0002_auto_20181026_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memberapp.GoodsColor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='价格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='spec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memberapp.GoodsDetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberapp.Goods'),
        ),
    ]
