# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-28 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20181127_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='color',
            field=models.CharField(max_length=50, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='spec',
            field=models.CharField(max_length=50, verbose_name='规格'),
        ),
    ]
