# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-28 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20181128_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='color',
            field=models.CharField(default=1, max_length=50, verbose_name='颜色'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='isfavorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favorite',
            name='spec',
            field=models.CharField(default=1, max_length=50, verbose_name='规格'),
            preserve_default=False,
        ),
    ]
