# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-28 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20181128_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='isfavorite',
        ),
    ]
