# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-28 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0003_auto_20181112_1646'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0006_remove_favorite_isfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buynow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='颜色')),
                ('spec', models.CharField(max_length=50, verbose_name='规格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('amount', models.IntegerField(default=0, null=True, verbose_name='数量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberapp.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
