# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-28 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_buynow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buynow',
            name='price',
        ),
    ]
