# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-06 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='goodsimg',
            field=models.ImageField(default='normal.png', upload_to='ordersgood', verbose_name='产品图'),
        ),
    ]
