# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-06 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordergoods_goodsimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='color',
            field=models.CharField(default=1, max_length=50, verbose_name='颜色'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='spec',
            field=models.CharField(default=1, max_length=50, verbose_name='规格'),
            preserve_default=False,
        ),
    ]
