# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-07 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20181206_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateTimeField()),
                ('logistics_company', models.CharField(max_length=50, verbose_name='物流公司')),
                ('express_number', models.IntegerField(verbose_name='快递编号')),
                ('information', models.CharField(max_length=200, verbose_name='物流信息')),
            ],
        ),
    ]
