# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-07 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_logistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
            preserve_default=False,
        ),
    ]
