# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-07 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_logistics_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=200, verbose_name='物流信息')),
            ],
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='information',
        ),
        migrations.AddField(
            model_name='logisticsinfo',
            name='logist',
            field=models.ManyToManyField(to='order.Logistics'),
        ),
    ]
